### ISSUE TITLE
Infinite loop in UIView parentController property on iOS 14.0-14.4

### ISSUE THREAD

**Issue by anivaros** [shaps80/SwiftUIBackports#23]
## General Information
See attached project

 - Project version:
1.6.3
 
 - Platform/OS version: 
iOS 14.0-14.4
 
 - IDE version:
Xcode 13
 
 - Devices: 
 
 
 - Any related GitHub issues:

## Describe the bug
Uninited tab body causes infinite loop in UIView parentController property 

## Steps to reproduce
1. Run attached project on iOS 14.0-14.4
2. Tap "Show modal" on tab A
3. Select TextField

## Expected behavior
No infinite loop in `OwningController.swift`

## Stack trace, compiler error, code snippets
[Archive.zip](https://github.com/shaps80/SwiftUIBackports/files/9525497/Archive.zip)

## Additional context
If tab B were opened before Modal, all works fine.

**Comment by shaps80** [comment]
Thank you for raising, will investigate 👍🏻

**Comment by anivaros** [comment]
This issue could occur in other scenarios, but this is simpler way to reproduce

**Comment by ChristopherCarranza** [comment]
Just ran into this as well with a TabView. Thank you for looking into it.

**Comment by shaps80** [comment]
I'm having trouble getting this issue to show up tbh. I've used your project and explored this myself but I cannot reproduce. Are you able to reproduce 100% of the time?

You mention above that the issue occurs in Xcode 13, but you saved the project using Xcode 14 beta, so I fixed that and tried in 13 but still no joy.

**Comment by anivaros** [comment]
Yes, 100%. Same problem on Xcode 14, no difference. 
Which simulator did you use? Just checked on Xcode 14 RC + iPhone 11 14.1, same problem.
<img width="1160" alt="Screenshot 2022-09-12 at 11 23 25" src="https://user-images.githubusercontent.com/873387/189606876-2f23895d-8040-4d5c-9f39-8d51cca5cbb0.png">

**Comment by shaps80** [comment]
Ok I'll try that, odd that its not 100% of the time for me. Thanks for checking, will try this now.

**Comment by anivaros** [comment]
I've got same problem on latest iOS with `.backport.scrollDisabled(true)` on code like this:
```swift
ScrollView {
    LazyVGrid(columns: [GridItem(.adaptive(minimum: 140))]) {
        rows
    }
}
.backport.scrollDisabled(true)
```
But I can't achieve this on minimal reproducible example :(

**Comment by shaps80** [comment]
Yeah I'm guessing its an issue in the view controller lookup code, I think I have an idea for fixing it overall.

**Comment by shaps80** [comment]
@anivaros I should have a new release out today/tomorrow that I _think_ resolves this issue completely.

**Comment by anivaros** [comment]
Great news! 🔥

**Comment by shaps80** [comment]
FYI I’ve fallen sick today, will get to this very soon, just need a couple days 👍🏻

**Comment by anivaros** [comment]
.@shaps80 I've checked, now all ok. Also checked issue with `.backport.scrollDisabled(true)` and `LazyVGrid`. Looks like now all works as expected 🎉
Thank you!!

**Comment by shaps80** [comment]
Amazing! Glad to hear. I'll get this in shortly :)

**Comment by shaps80** [comment]
You’ll need to provide a failing demo project to be helpful here. 

Also please create a new issue since this is slightly unrelated to initial issue and this was resolved, thanks.
