### ISSUE TITLE
Mac Catalyst app build fails on Xcode 14 RC

### ISSUE THREAD

**Issue by anivaros** [shaps80/SwiftUIBackports#24]
## General Information
Catalyst app build fails on Xcode 14 RC with `redefinition of module 'QuickLook'` error

 - Project version:
1.4.0-1.6.3
 
 - Platform/OS version: 
macOS Catalyst
 
 - IDE version:
Xcode 14 RC

**Comment by anivaros** [comment]
My mac catalyst app version is not in production yet, so it's not critical problem for me, but FYI 🙂

**Comment by shaps80** [comment]
To be honest I have not tested the entire library properly to know if its Catalyst compatible or not. This was never a project goal I guess so may take a while (if at all) for me to look at. But thanks for reporting.

**Comment by shaps80** [comment]
Looks like @mikakruschel has fixed this issue 👍

**Comment by anivaros** [comment]
Oh my! Eagle eye @mikakruschel 👏
