### ISSUE TITLE
Issues with project setup

### ISSUE THREAD

**Issue by X901** [shaps80/SwiftUIBackports#28]
Hi, 
Everytime I install your library I got these errors
BTW my minimum target is iOS 15 !

<img width="494" alt="Screen Shot 2022-10-18 at 3 07 00 PM" src="https://user-images.githubusercontent.com/16876982/196425393-b5122c91-f383-41db-9047-653b82ee4214.png">

**Comment by shaps80** [comment]
I'm gonna need a sample project I'm afraid. Multiple other projects (not only mine) are using this without issue on iOS 13+ (and other  platforms) so it'll be some weird setup most likely.

**Comment by anivaros** [comment]
@X901 maybe you're using old Xcode version (lower 13.2)?

**Comment by anivaros** [comment]
@X901 apple back ported concurrency to iOS 13 only in Xcode 13.2: https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes#Swift

So there is no bug.

**Comment by shaps80** [comment]
Oh good catch @anivaros and thank you for helping out! I had considered Xcode version but I had forgotten that the backport came later 👍👍👍
