### ISSUE TITLE
Not Dismissing

### ISSUE THREAD

**Issue by tazmancoder** [shaps80/SwiftUIBackports#30]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

## General Information

 - Project version:
 
1.2.0
 
 - Platform/OS version: 
 
iOS 16.1
 
 - IDE version:
 
Xcode 14.1
 
 - Devices: 
 
 Real iPhone 13, Simulator iPhone 14 Pro Max

 - Any related GitHub issues:

## Describe the bug
*Clearly and concisely describe the bug.*
I am using ActivityView in one of my Apps. I have noticed that if you bring up the activity view and choose to email or text or anything else. If you cancel the email or text the activity view doesn’t dismiss it stays on top of the screen. I can’t seem to figure out why this is not dismissing. Any help or advice would be appreciated….

## Steps to reproduce
*Provide numbered steps to follow that reproduce the bug.*
1. Bring up an activity view
2. Choose to email
3. Then hit cancel when MailView comes up
4. You'll notice the MailVIew goes away but the share sheet stays on the screen

## Expected behavior
*Clearly and concisely describe what you expected to happen.*
I would expect that if you canceled whatever activity you've chosen the share sheet should dismiss and go away

## Stack trace, compiler error, code snippets
*Paste the full output of any stack trace or compiler error.*
*Include a code snippet that reproduces the described behavior, if applicable*

## Screenshots
*If applicable, add screenshots, gifs, or videos to help explain your problem.*

## Additional context
*Add any other useful information about the problem here.*

**Comment by shaps80** [comment]
I don’t think this is related to this repo?

**Comment by tazmancoder** [comment]
I think it might be. Only reason I say that is because it the activity view that doesn’t dismiss.If I’m wrong I apologize,-Mark/*Mark PerrymanApple (MAC) Enthusiast(435) 882-1008On Nov 15, 2022, at 13:08, Shaps ***@***.***> wrote:﻿
I don’t think this is related to this repo?

**Comment by shaps80** [comment]
What I mean is, `ActivityView` doesn't even exist in this repo ;)
Its a fairly self-contained component too, so its almost certainly on that repo I'm afraid.

**Comment by tazmancoder** [comment]
Ok,I see what you mean. I was looking at it and I think if you decide to cancel the email or text or whatever the activity view won’t dismiss and probably shouldn’t that way you can choose another way to share.Thanks,-Mark/*Mark PerrymanApple (MAC) Enthusiast(435) 882-1008On Nov 18, 2022, at 08:26, Shaps ***@***.***> wrote:﻿
What I mean is, ActivityView doesn't even exist in this repo ;)
Its a fairly self-contained component too, so its almost certainly on that repo I'm afraid.
