### ISSUE TITLE
Does .backports.onChange {} really work on macOS 10.15 Catalina?

### ISSUE THREAD

**Issue by ShikiSuen** [shaps80/SwiftUIBackports#33]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

## General Information
I tried this on my macOS 10.15 virtual machine but find that it doesn't execute the  {}-bracketed contents at all.

 - Project version: [v1.8.2](https://github.com/shaps80/SwiftUIBackports/releases/tag/1.8.2)
 
 - Platform/OS version: macOS 10.15 Catalina.
 
 - IDE version: Xcode 14.
 
 - Devices: VMWare Fusion 13 running on mac mini (macOS 13).
 
 - Any related GitHub issues:

## Describe the bug
(See general information.)

-------

**I have no way to create a standalone project demonstrating this issue due to the failure of compiling this package in a new project (targeting macOS 10.15). Once this compilation issue gets solved, I can provide a bare-bone project demonstrating this issue.**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3164826/205787565-512d1577-eec3-4f9b-a5fb-97d8878b9b8c.png">

-------

## Steps to reproduce
*Provide numbered steps to follow that reproduce the bug.*

## Expected behavior
*Clearly and concisely describe what you expected to happen.*

## Stack trace, compiler error, code snippets
*Paste the full output of any stack trace or compiler error.*
*Include a code snippet that reproduces the described behavior, if applicable*

## Screenshots
*If applicable, add screenshots, gifs, or videos to help explain your problem.*

## Additional context
*Add any other useful information about the problem here.*

**Comment by shaps80** [comment]
I’m confused by the title here. Are you saying the project doesn’t compile against macOS using the latest release?

If you’re talking about an unreleased version that could be true but I wasn’t aware of any release builds having this issue atm?

**Comment by shaps80** [comment]
@ShikiSuen thanks for letting me know.

It _could be_ in the framework but I’ve not had other reports like this and its been working for me fine across several projects so I’m unaware of any issues sorry.

Do let me know if you discover it is on my end though, as I’d want to know for sure 👍🏻
