### ISSUE TITLE
Readme details about a PageView but library doesn't currently include it.

### ISSUE THREAD

**Issue by Prince2k3** [shaps80/SwiftUIBackports#40]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

## General Information
The Readme specifies a PageView but the library version doesn't have one. 

 - Project version:
Latest
 
 - Platform/OS version: 
N/A
 
 - IDE version:
N/A
 
 - Devices: 
N/A
 
## Steps to reproduce
* Load library via SPM
* Try to use PageView
* Notice PageView doesn't exist

## Expected behavior
PageView should exist according to Readme

**Comment by shaps80** [comment]
Thanks, I've updated the README 👍
