### ISSUE TITLE
toolbarBackground style modifier

### ISSUE THREAD

**Issue by Alex293** [shaps80/SwiftUIBackports#49]
Hi, thanks for the nice work on the package !

I see that `public func toolbarBackground<S>(_ style: S, for bars: ToolbarPlacement...) -> some View where S : ShapeStyle` is commented, what is blocking/missing for making it usable ?

**Comment by shaps80** [comment]
I attempted working on this, it proved to be quite difficult to backport without issues/bugs being introduced. Particularly surrounding how largeTitle backgrounds work during scroll events. 

I didn't have the time to investigate further, but I did spend a fair amount of time (failing) trying to implement this.

To me, it looks unlikely I'm afraid. If you decided to continue/attempt this please test carefully across all potential uses of the toolbar (even if its just iOS) – thanks!

**Comment by Alex293** [comment]
Thanks for the quick response. I'm evaluating if it's worth the effort compared to make a custom navbar for our app. I'll try investigating and report here if I find a working solution.

**Comment by shaps80** [comment]
Yeah mines essentially a refactor of that library, I felt it simplifies some of the APIs in that library. Regardless I don't want to include any other dependencies so that's why I did it this way. Thanks!
