### ISSUE TITLE
crash on iOS 13 and iOS 14

### ISSUE THREAD

**Issue by SouHanaQiao** [shaps80/SwiftUIBackports#59]
0x109a982fc <+0>:
sub
sp，sp，#0x40

x20，x19，[sp，#0x20]
0x109a98300 <+4>:
stp
0x109a98304 <+8>:
x29，x3日，[sp，#0x3日]
stp
0x109a98308 <+12>:

mov
x19，x0
0x109a9830c <+16>:
x8，10606
adrp

日x109a9831日 <+20>:addnominal type descriptor forBGFoundation.PhotosViewController.Coordinator + 76
x8，x8，#0x8
0x109a98314 <+24>: adrp
x9，106日6
0x109a98318 <+28>:; nominal type descriptor foraddBGFoundation.PhotosViewController.Coordinator + 109
x9，x9，#9x20
0x109a9831c <+32>:
x8，x9，[sp]
stp
0x109a98320 <+36>:
mov
w日，#0x13f
0x10c155514
0x109a98324 <+40>:
bl
; symbol stub for: type metadata accessor for
PhotosUI.PHPickerConfiguration
x1，#0x3f
0x109a98328 <+44>:
cmp
0x109a9832c <+48>:
b.hi
0x109a9836c
; <+112>
0x109a98330 <+52>:
add
x4，x19，#0x5日
ldur
x8，[x日，#-0x8]
0x109a98334 <+56>:
0x109a98338 <+60>:
add
x8，x8，#0x40
0x109a9833c <+64>:
adrp
x9，10606
0x109a98340 <+68>:
add
x9，x9，#0x38
;nominal type descriptor for
BGFoundation.PhotosViewController.Coordinator + 1240x109a98344 <+72>:stp0x109a98348 <+76>:mov
x8，x9，[sp，#0x10]

x3，sp
日x109a9834c <+80>:mov
x0，x19
0x109a98350 <+84>:mov
w1，#0x100
0x109a98354 <+88>:mov
w2，#Ox4
67
0x109a98358 <+92>:
0x10c15cfc日
;symbol stub for: swift updateClassMetadata2
x日，#0x日
0x109a9835c <+96>:cmp
0x109a98360 <+100>:csel
x日， x日， xzr, ne
0x109a98364 <+104>: csel
x1，x1，xzr,ne

**Comment by shaps80** [comment]
Apologies but the photos picker is not yet released. I know it showed up (accidentally) in a release so perhaps that was confusing, I will be removing it temporarily.
