### ISSUE TITLE
Refreshable not enabling pull-to-refresh

### ISSUE THREAD

**Issue by JosephDuffy** [shaps80/SwiftUIBackports#7]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

## General Information

 - Project version:
1.0.9
 
 - Platform/OS version: 
iOS 14.0.1, iOS 15.5, iOS 16
 
 - IDE version:
Xcode 13.4.1, Xcode 14 beta 2
 
 - Devices: 
iPhone Simulator
 
 - Any related GitHub issues:
N/A

## Describe the bug
Using `.backport.refreshable` does not add pull-to-refresh to a list.

## Steps to reproduce
Add `.backport.refreshable` to a `List`.

## Expected behavior
Should add pull-to-refresh to the list.

## Stack trace, compiler error, code snippets

```swift
struct RootView: View {
    var body: some View {
        TabView {
            NavigationView {
                List {
                    Text("1")
                    Text("2")
                    Text("3")
                }
                .navigationTitle("Native")
                .refreshable {
                    print("Refresh!")
                }
            }
            .tabItem {
                Text("Native")
            }

            NavigationView {
                List {
                    Text("1")
                    Text("2")
                    Text("3")
                }
                .navigationTitle("Backport")
                .backport.refreshable {
                    print("Refresh!")
                }
            }
            .tabItem {
                Text("Backport")
            }
        }
    }
}
```

## Screenshots

![Simulator Screen Shot - iPhone 12 mini - 2022-06-30 at 21 03 35](https://user-images.githubusercontent.com/1325813/176822212-d3efc5ef-baca-40e0-bada-52582bb991f9.png)
![Simulator Screen Shot - iPhone 12 mini - 2022-06-30 at 21 03 28](https://user-images.githubusercontent.com/1325813/176822216-41c4ed84-f7df-49d2-8870-07d532ba796d.png)

## Additional context
It could be argued that the backport is complete; it does set the environment value. But not adding the pull-to-refresh was a surprise to me. It does look to be possible (https://github.com/Geri-Borbas/iOS.Package.Refreshable) so maybe something similar could be added?

**Comment by shaps80** [comment]
Yeah, I basically include the basic mechanism only for now. I had intended to explore this and I in fact have it listed (need to add my list to GH Issues 😬). I'll check it out thanks!

**Comment by shaps80** [comment]
One other note, I needed to backport `ProgressView` first as well, so that was another reason I bumped the core-implementation, preferring to explore pull-to-refresh options later on.

**Comment by JosephDuffy** [comment]
Awesome! I'll try it out soon :)
