### ISSUE TITLE
Apple privacy manifest

### ISSUE THREAD

**Issue by skyfoxa** [shaps80/SwiftUIBackports#70]
## Describe the feature
Because the library uses `UserDefaults`, it has to contain PrivacyInfo manifest, check [Apple doc](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401)

## Is your feature request related to a problem? 

> Starting March 13: If you upload a new or updated app to App Store Connect that uses an API requiring approved reasons, we’ll send you an email letting you know if you’re missing reasons in your app’s privacy manifest. This is in addition to the existing notification in App Store Connect.
> 
> Starting May 1: You’ll need to include approved reasons for the listed APIs used by your app’s code to upload a new or updated app to App Store Connect. If you’re not using an API for an allowed reason, please find an alternative. And if you add a new third-party SDK that’s on the list of commonly used third-party SDKs, these API, privacy manifest, and signature requirements will apply to that SDK. Make sure to use a version of the SDK that includes its privacy manifest and note that signatures are also required when the SDK is added as a binary dependency.

https://developer.apple.com/news/?id=3d8a9yyh

## Proposed solution
Add Privacy manifest supporting UserDefaults privacy reason type, https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by shaps80** [comment]
Thanks, I'd love a submission for this, from anyone having the time. I honestly don't have any time for this atm.

**Comment by skyfoxa** [comment]
@shaps80 ok, I created a PR https://github.com/shaps80/SwiftUIBackports/pull/71 for this issue. Will you have time to review it?

**Comment by shaps80** [comment]
Yep, just did. LGTM, I'll get this merged tomorrow thanks!

**Comment by shaps80** [comment]
@skyfoxa this is now merged and included in v2.8.1 👍
